# Whenever a tag push matching pattern "v*" then run the job
on:
  push:
    branches:
      - master

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:

      # Always include the checkout step so that
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v3.3.0

    - name: calculate version
      run: echo "v1.0.$(git rev-list --count HEAD)" > version.tres

    - name: get tag from version
        id: tag_version
        run: echo "TAG_VERSION=$(cat version.tres)" >> $GITHUB_OUTPUT

    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v5.2.1
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
        cache: true
        relative_project_path: ./
        archive_output: true
        archive_root_folder: true

      # This release action has worked well for me. However, you can most likely use any release action of your choosing.
      # https://github.com/ncipollo/release-action
    - name: create release
      uses: ncipollo/release-action@v1.13.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ steps.tag_version.outputs.TAG_VERSION }}
        commit: ${{ github.ref }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
